version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes --appendfsync everysec

  petwell:
    container_name: petwell
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - redis
    env_file:
      - .env
    command: ["node", "dist/main.js"]
    restart: unless-stopped

volumes:
  redis_data:
